# Generated by Django 5.2.1 on 2025-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
